### ISSUE TITLE
Velodyne 16 line radar cannot complete calibration

### ISSUE THREAD

**Issue by af-doom** [koide3/direct_visual_lidar_calibration#13] opened 2023-05-01 12:31 UTC
**Before opening an issue**
If the issue is about build errors:
- [1] I have read [installation instructions](https://koide3.github.io/direct_visual_lidar_calibration/installation/)
- [1] I have considered using [docker](https://koide3.github.io/direct_visual_lidar_calibration/docker/)

If the issue is about calibration procedure and results:
- [1] I have read [data collection instructions](https://koide3.github.io/direct_visual_lidar_calibration/collection/)
- [1] I have confirmed [the program works on example data](https://koide3.github.io/direct_visual_lidar_calibration/example/)

If the issue is about the algorithm:
- [ ] I have read [the paper](https://staff.aist.go.jp/k.koide/assets/pdf/icra2023.pdf)

**Describe the bug**
Unable to generate dense point clouds during the data processing stage of velodyne16 line LiDAR
![2023-04-13 10-53-58 的屏幕截图](https://user-images.githubusercontent.com/91470350/235451897-15c49cfd-d4a7-4d08-a80d-867ebd71e12e.png)
nable to generate dense point clouds during the data processing stage of velodyne16 line LiDAR

**To Reproduce**

**Expected behavior**

**Screenshots and sample data**
If applicable, add screenshots and sample data to reproduce your problem.

**Environment:**
 - OS:Ubuntu 20.04
 - ROS version: ROS1 noetic

**Additional context**

**Comment by Ning030** [comment] 2023-06-29 06:14
Have you solved this problem? If so, can you provide a solution? Thanks Thanks!

**Comment by koide3** [comment] 2023-07-05 01:33
Can anybody provide an example rosbag to reproduce the issue?

**Comment by af-doom** [comment] 2023-07-05 06:28
> Have you solved this problem? If so, can you provide a solution? Thanks Thanks!

sorry ,no

**Comment by Ning030** [comment] 2023-07-18 06:44
This is a ROS1 bag that I recorded myself.
[(https://drive.google.com/file/d/1Z_S8l-WU6jQWuUJfvNQVFbGRWMgjAY2d/view?usp=sharing)](url)
 This is a robosence 16 line LiDAR .
Unable to generate dense point clouds during the data processing stage!!!

**Comment by koide3** [comment] 2023-07-19 23:53
Hi @Ning030 ,
Thanks for providing the rosbag. I found that the issue stems from input point clouds containing NaN points. I added a filter to remove invalid points and pushed the updated code to `vlp16` branch, which will be merged into `main` soon.

**Comment by Ning030** [comment] 2023-07-20 10:13
Thank you for your answer. I greatly admire your excellent work！！
I would like to ask, **how to use the automatic initial guess（SuperGlue）**?
 I downloaded the [source code](https://github.com/magicleap/SuperGluePretrainedNetwork), but the calibration effect is not good.
Did you retrain it？

**Comment by koide3** [comment] 2023-07-24 04:28
The accumulation result may not have a sufficient point density required for the automatic initial guess pipeline. Try to increase the  LiDAR data (with up-down movement) or to use the manual initial guess interface.

**Comment by Ning030** [comment] 2023-07-28 08:01
Thank you for your suggestion. 
But I still have **poor calibration results** when **using the data you provided** to run the algorithm. （With automatic initial guess）.
Why is this?

**Comment by Ning030** [comment] 2023-08-02 02:38
Sorry！
 I found out that it was caused by my input of wrong camera intrinsic data. 
Thank you for making this work public.

**Closed** 2023-08-03 02:55 UTC
Labels: bug
